### ISSUE TITLE
Add the last-synced time of a link to the link detail page.

### ISSUE THREAD

**Issue by 1egoman** [backstrokeapp/dashboard#1]
Currently, it's not possible to see the last-sync time of a Backstroke link in the dashboard. This is available within the [`link-detail` component](https://github.com/backstrokeapp/dashboard/tree/master/src/components/link-detail) as `this.props.initialLinkState.lastSyncedAt`. Ideally, the last-synced time should be placed below the switch and resync buttons in the UI, something like the below, though if you have a better and more creative solution, that would be even better!

<img width="409" alt="screen shot 2017-10-08 at 11 24 18 am" src="https://user-images.githubusercontent.com/1704236/31318139-4aa61a58-ac1b-11e7-8452-a72f22cfe679.png">

**Comment by recrsn** [comment]
Hi! I'm interested to work on this issue.

> though if you have a better and more creative solution, that would be even better!

I was thinking of using relative times (like 2 hours ago) instead of absolute times.
