### ISSUE TITLE
Add a button to refresh the last synced time

### ISSUE THREAD

**Issue by 1egoman** [backstrokeapp/dashboard#3]
The Backstroke dashboard currently doesn't have a way to update the last-synced time of a link without reloading the page. Ideally, there'd be a refresh button next to the text added in https://github.com/backstrokeapp/dashboard/pull/2 that refreshes the state of the link that's currently visible, pulling in a new refresh time from the server.

<img width="609" alt="screen shot 2017-10-08 at 3 06 31 pm" src="https://user-images.githubusercontent.com/1704236/31319949-504edfde-ac3a-11e7-80d1-14f58ef9b509.png">

This application uses redux for state management. There's an action named `COLLECTION_LINKS_PUSH` that merges new server state into the links collection (link to [action](https://github.com/backstrokeapp/dashboard/blob/master/src/actions/collection/links/push.js) and [the section of the links reducer that handles the action](https://github.com/backstrokeapp/dashboard/blob/master/src/reducers/links/index.js#L48-L65)). 

When the user clicks the refresh button, you'll need to dispatch an action that fetches the data for the currently selected link (the id of the selected link is available in the `link-detail` component as `link.id`), and call the `COLLECTIONS_LINKS_PUSH` action mentioned above with that data. The http request required to fetch this data is `GET https://api.backstroke.co/v1/links/:id`.

If you'd like to see an example of an action that does something very similar, check out [this](https://github.com/backstrokeapp/dashboard/blob/master/src/actions/collection/links/fetch.js) action. It's used to fetch all links when initially loading the `link-list` page (the list view) of the dashboard. 

If you'd like clarification on the structure of the application, I'l more than willing to help or answer questions. Thanks!

**Comment by Jeffrey-Chang** [comment]
@1egoman Would you mind if I tried to pick this one up?

**Comment by 1egoman** [comment]
@Jeffrey-Chang Go for it!

It's a bit dependent on https://github.com/backstrokeapp/dashboard/issues/1, but I think you should be able to implement the refresh button separately and bring in the last synced label once complete. Would you agree?

Thanks for helping out with Backstroke!

**Comment by Jeffrey-Chang** [comment]
@1egoman Yes, I can complete this separately

**Comment by 1egoman** [comment]
I was able to close https://github.com/backstrokeapp/dashboard/issues/1.
